version: '3'

services:
  db:
    image: mongo
    ports:
      - '27018:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=krimi
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=auth
      - MONGO_USERNAME=krimi
      - MONGO_PASSWORD=root
    volumes:
      - ./data:/data/db
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
  cache:
    image: redis
    ports:
      - '6379:6379'
    command: ['--requirepass', 'secret']
